### ISSUE TITLE
Training data release

### ISSUE THREAD

**Issue by mktaylor4** [labstructbioinf/rossmann-toolbox#10]
Was wondering if you had uploaded or included a compressed version of your training data (also segmented into train,val,test) anywhere? I saw your methods of data curation from PDB and various preprocessing pipelines in the main text and supplemental, but was wanting the specific partitioning of the dataset  (or at least random state if I attempt to follow main text and recapitulate the data myself)

**Comment by staszekdh** [comment]
@mktaylor4 All data will be added to this repository soon. Should we also add the scripts to generate them?

**Comment by mktaylor4** [comment]
could be helpful to add scripts for ease of generation! up to you!

**Comment by staszekdh** [comment]
@mktaylor4  We have placed the training data in https://github.com/labstructbioinf/rossmann-toolbox/tree/main/data (a pickle file with sequences and annotations, and an archive with PDB structures). Note that this dataset is highly redundant and will shrink significantly after removing entries with identical sequences. If you need additional data and/or train/test splits, please let me know. We have not uploaded the data generation scripts as they are too messy to include in the repository, but if that would be helpful I can either send you what we have or do some cleaning up and put them here.
