### ISSUE TITLE
ValueError indicating size change and binary incompatibility with greenlet

### ISSUE THREAD

**Issue by puzhongji-CADEE** [labstructbioinf/rossmann-toolbox#11]
Hello,

While trying to use the rossmann_toolbox, I encountered the following error:

ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 40 from PyObject

This issue typically suggests a mismatch between the compiled C headers and the binary version being used at runtime.

Environment Details:
OS: [Your OS, e.g., "Ubuntu 20.04"]
Python Version: [Your Python version, e.g., "Python 3.7.10"]

**Comment by staszekdh** [comment]
@puzhongji-CADEE  We have updated the main README with new installation instructions. Currently only the sequence-based version works (the structure-based model is being rebuilt and will be available soon). Could you please test the installation?

**Comment by puzhongji-CADEE** [comment]
## Issue Description
After successfully running `example_minimal.ipynb`, I encountered a `ValueError` when attempting to predict with a valid input dictionary using `RossmannToolbox`. Despite providing a non-empty dictionary, the error `Empty dictionary was passed as an input!` is raised.

## Steps to Reproduce
1. Ensure that `example_minimal.ipynb` runs without issues.
2. Install RossmannToolbox with GPU support.
3. Execute the following code snippet:

```python
import matplotlib.pylab as plt
from rossmann_toolbox import RossmannToolbox
rtb = RossmannToolbox(use_gpu=True)

# Example 1
# The b-a-b core is predicted in the full-length sequence

data = {'8C6A_A': 'RSTLVHWFRKGLRLHDNPALSHIFTAANAAPGRYFVRPIFILDPGILDWMQVGANRWRFLQQTLEDLDNQLRKLNSRLFVVRGKPAEVFPRIFKSWRVEMLTFETDIEPYSVTRDAAVQKLAKAEGVRVETHCSHTIYNPELVIAKNLGKAPITYQKFLGIVEQLKVPKVLGVPEKLKNMPTPPKDEVEQKDSAAYDCPTMKQLVKRPEELGPNKFPGGETEALRRMEESLKDEIWVARFEKPNTAPNSLEPSTTVLSPYLKFGCLSARLFNQKLKEIIKRQPKHSQPPVSLIGQLMWREFYYTVAAAEPNFDRMLGNVYCMQIPWQEHPDHLEAWTHGRTGYPFIDAIMRQLRQEGWIHHLARHAVACFLTRGDLWISWEEGQRVFEQLLLDQDWALNAGNWMWLSASAFFHQYFRVYSPVAFGKKTDPQGHYIRKYVPELSKYPAGCIYEPWKASLVDQRAYGCVLGTDYPHRIVKHEVVHKENIKRMGAAYKVNREV'}

preds = rtb.predict(data, mode='seq', core_detect_mode='dl', importance=False)
print(preds)
