### ISSUE TITLE
seqvec weights download progress bar does not work

### ISSUE THREAD

**Issue by staszekdh** [labstructbioinf/rossmann-toolbox#5]
This shows up instead of the progress bar:
```
HBox(children=(FloatProgress(value=0.0, max=347361261.0), HTML(value='')))
```

**Comment by jludwiczak** [comment]
I didn't plan it as a feature, it's handled by the `torch.hub.download_url_to_file` method so perhaps it requires something on the jupyter side. If needed progress bar can be disabled by setting `progress=False` in this method.
